name: StrawChest
main: bzh.strawberry.chest.core.StrawChest
version: 0.0.1-ALPHA
authors:
  - Eclixal
  - Uicias
api-version: 1.15
depend:
  - StrawCore
commands:
  givekey:
    description: Permet aux Administrateurs de give des clés
    permission: strawchest.admin
  cle:
    description: Permet aux joueurs de récuperer les items en attentes
    permission: strawchest.cle
    aliases:
      - cles
      - crclaim